"""Track when a paper's text changes, separately from when it was last fetched.

Additive and compatible with the previous application: the hash is generated by
PostgreSQL and the other columns have defaults, so an older importer can still write.
"""

from alembic import op

revision = "0002"
down_revision = "0001"
branch_labels = None
depends_on = None


def upgrade():
    op.execute("""
        ALTER TABLE papers
            ADD COLUMN content_hash CHAR(32) GENERATED ALWAYS AS (
                md5(title || E'\\n' || coalesce(abstract, ''))
            ) STORED,
            ADD COLUMN content_revision INTEGER NOT NULL DEFAULT 1,
            ADD COLUMN content_changed_at TIMESTAMPTZ;
        -- The true change time of existing rows is unknown; the last import is an upper bound.
        UPDATE papers SET content_changed_at = updated_at;
        ALTER TABLE papers
            ALTER COLUMN content_changed_at SET NOT NULL,
            ALTER COLUMN content_changed_at SET DEFAULT now();
    """)


def downgrade():
    op.execute("""
        ALTER TABLE papers
            DROP COLUMN content_hash,
            DROP COLUMN content_revision,
            DROP COLUMN content_changed_at
    """)
